# Generated by Django 4.1.2 on 2022-11-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=15)),
                ('hora_llegada', models.IntegerField(max_length=15)),
                ('minutos_llegada', models.IntegerField(max_length=15)),
                ('hora_salida', models.IntegerField(max_length=15)),
                ('minutos_salida', models.IntegerField(max_length=15)),
            ],
        ),
    ]
