# Generated by Django 4.1.2 on 2022-12-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionitinerario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerario',
            name='ruta',
            field=models.CharField(choices=[('ruta1', 'ruta 1'), ('ruta2', 'ruta 2'), ('ruta3', 'ruta 3'), ('ruta4', 'ruta 4'), ('ruta5', 'ruta 5'), ('ruta6', 'ruta 6'), ('ruta7', 'ruta 7'), ('ruta8', 'ruta 8'), ('ruta9', 'ruta 9')], default='ruta1', max_length=15),
        ),
    ]
