# Generated by Django 4.1.2 on 2022-10-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('rpassword', models.CharField(max_length=20)),
            ],
        ),
    ]
