# Generated by Django 4.1.5 on 2023-01-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'verbose_name': 'Reservación', 'verbose_name_plural': 'Reservaciones'},
        ),
    ]
