# Generated by Django 4.1.5 on 2023-01-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvehiculo', '0002_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='Matricula',
            field=models.CharField(max_length=7),
        ),
    ]
