# Generated by Django 4.1.2 on 2022-11-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reservacion', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=15)),
                ('cantidad_km', models.IntegerField()),
                ('costo', models.IntegerField()),
            ],
        ),
    ]
