# Generated by Django 4.1.2 on 2022-12-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontarifa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='tipo_reservacion',
            field=models.CharField(choices=[('mantenimiento', 'mantenimiento'), ('pasaje', 'pasaje'), ('carga', 'carga')], default='mantenimiento', max_length=15),
        ),
    ]
