# Generated by Django 4.1.2 on 2022-12-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontarifa', '0002_alter_tarifa_tipo_reservacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='tipo_reservacion',
            field=models.CharField(choices=[('mantenimiento', 'mantenimiento'), ('pasaje', 'pasaje'), ('carga', 'carga')], max_length=15),
        ),
    ]
