# Generated by Django 4.1.2 on 2022-12-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontarifa', '0003_alter_tarifa_tipo_reservacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='cantidad_pasajeros',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='cantidad_peso',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='cantidad_km',
            field=models.IntegerField(null=True),
        ),
    ]
