# Generated by Django 4.1.5 on 2023-01-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontarifa', '0004_tarifa_cantidad_pasajeros_tarifa_cantidad_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='cantidad_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='cantidad_pasajeros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='cantidad_peso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
