# Generated by Django 4.1.2 on 2022-10-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=7)),
                ('fecha', models.CharField(max_length=7)),
                ('tipo', models.CharField(max_length=7)),
                ('vehiculo', models.CharField(max_length=7)),
                ('costo', models.IntegerField()),
            ],
        ),
    ]
