# Generated by Django 4.1.5 on 2023-01-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvehiculo', '0002_alter_vehiculo_options'),
        ('gestionreservacion', '0003_alter_reservacion_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='vehiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionvehiculo.vehiculo'),
        ),
    ]
