# Generated by Django 4.1.5 on 2023-01-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionreservacion', '0004_alter_reservacion_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='telefono',
            field=models.CharField(max_length=8),
        ),
    ]
