# Generated by Django 4.1.5 on 2023-01-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionreservacion', '0006_alter_reservacion_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='telefono',
            field=models.CharField(max_length=8),
        ),
    ]
