# Generated by Django 4.1.5 on 2023-01-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionreservacion', '0007_alter_reservacion_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='mes',
        ),
        migrations.AddField(
            model_name='reservacion',
            name='fecha',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
