# Generated by Django 4.1.5 on 2023-02-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionreservacion', '0009_alter_reservacion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='costo',
        ),
    ]
